title        = "The Reactive Foundation"
baseURL      = "https://reactive.foundation"
languageCode = "en-us"
disableKinds = ["taxonomy", "taxonomyTerm"]
[markup.goldmark.renderer]
unsafe= true

[permalinks]
news = "/news/:year/:month/:day/:title"
